image_speed = 0.35
alarm[1] = 60
global.seconds = 40
global.minutes = 3
frame = 0
chargecamera = 0
display_set_gui_size(960, 540)
surface_resize(application_surface, display_get_gui_width(), display_get_gui_height())
global.panicbg = true
global.maxwave = 13200
global.wave = 0
global.paniclayercount = 0
speedbar_index = 0
speedbar_spr = spr_speedbar
player_spr = spr_pepinoHUD
collect_spr = spr_sausagecollect
pizzacoin_timer = 0
pizzacoin_timermax = 300
pizzacoin_alpha = 0
shake_mag = 0
shake_mag_acc = 0
timestop = 1
camx = 0
camy = 0
textx = 480
texty = 600
showtext = false
text = ""
