if ((place_meeting((x + 1), y, obj_player) || place_meeting((x - 1), y, obj_player)) && obj_player.state == states.barrelroll)
    instance_destroy()
if (place_meeting(x, (y - 15), obj_player) && obj_player.state == states.barrelroll)
    instance_destroy()
if (place_meeting(x, (y + 15), obj_player) && obj_player.state == states.barrelroll)
    instance_destroy()
