pause = false
pause_menu = [["RESUME GAME", pause_resume], ["RESTART LEVEL", pause_restart], ["EXIT GAME", pause_exit]]
menuX = 1110
menuY = 690
menuInX = 910
menuInY = 290
menuOutX = 1110
menuOutY = 690
bgAlpha = 0
bgX = 960 + sprite_get_width(spr_pauseBG)
bgY = 540
collectAlpha = 0
collectSpr = spr_sausagecollect
selection = 0
screensprite = -4
depth = -9999
